version: '3.9'

services:
  postgres-local:
    container_name: postgres-local
    image: postgres
    ports:
      - '${DB_PORT}:5432'
    environment:
      POSTGRES_USER: '${DB_USERNAME}'
      POSTGRES_PASSWORD: '${DB_PASSWORD}'
      POSTGRES_DB: '${DB_NAME}'
    volumes:
      - ./data/db-dev:/var/lib/postgresql/data
    networks:
      - postgres

  pgadmin-local:
    container_name: pgadmin-local
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: '${PG_ADMIN_EMAIL}'
      PGADMIN_DEFAULT_PASSWORD: '${PG_ADMIN_PASSWORD}'
    ports:
      - "5050:80"
    networks:
      - postgres

networks:
  postgres:
    driver: bridge
