version: '3.9'

services:
  postgres-e2e:
    container_name: postgres-e2e
    image: postgres
    ports:
      - '${DB_PORT}:5432'
    environment:
      POSTGRES_USER: '${DB_USERNAME}'
      POSTGRES_PASSWORD: '${DB_PASSWORD}'
      POSTGRES_DB: '${DB_NAME}'
    volumes:
      - ./test/data/db:/var/lib/postgresql/data
    networks:
      - postgres

  pgadmin-e2e:
    container_name: pgadmin-e2e
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: '${PG_ADMIN_EMAIL}'
      PGADMIN_DEFAULT_PASSWORD: '${PG_ADMIN_PASSWORD}'
    ports:
      - "5051:80"
    networks:
      - postgres

networks:
  postgres:
    driver: bridge

